CREATE TABLE USERS(
  uuid VARCHAR(255) PRIMARY KEY NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

---- #

CREATE TABLE VERSION(
  version VARCHAR(255) PRIMARY KEY NOT NULL
);

---- #

INSERT INTO VERSION(version) VALUES('0.0.1');